### ISSUE TITLE
decrease mqqt update frequency

### ISSUE THREAD

**Issue by sla-te** [hsakoh/switchbot-mqtt#19]
For me the temperature on a connected hub2 will not refresh if the value has not changed. Changing this was somehow possible through redefining the sensor in configuration.yaml and settings the force_update: true paramater but this workaround seems to have stopped working. Can you add a switch so we can enable it?

ref.:
force_update: https://www.home-assistant.io/integrations/sensor.mqtt/#force_update

**Comment by hsakoh** [comment]
Thank you for the feedback.

Firstly, let me explain some aspects of the current specification of this add-on...

* It does not support overriding detection properties.
Specifically, the add-on does not subscribe to detection topics, so even if you override force_update, it cannot read it.
(You mentioned, "this workaround seems to have stopped working," but this aspect has not changed consistently since the past.)

* Here's a screenshot of the debug information for an MQTT device. The subscribed status update topic sends messages regardless of value changes.
Since the add-on does not internally maintain state, it sends all values received from polling or webhook.
This means it behaves as if force_update=true at all times.
![image](https://github.com/hsakoh/switchbot-mqtt/assets/20980395/19a14453-2926-4180-8039-53065552cb67)

---
Could you please provide more details about what you want to achieve?
Is it among the following?

* "I want to receive values at a frequency higher than the automatic polling frequency."
(Currently, since it doesn't internally maintain state, it's difficult to determine if the value has changed...)

* "I want to avoid sending messages to the status update topic if the value hasn't changed."
(In this case, I interpreted it as wanting force_update:false...)

**Comment by hsakoh** [comment]
I'm sorry, but since I only have MQTT devices created by myself, even when setting force_update:true, there are no devices with changing expressions...

Considering the 10-second interval, it seems to be "I want to receive values at a frequency higher than the automatic polling frequency."
In other words, I understand that you want to render more data points (with the same value repeatedly) at a frequency finer than the automatic polling frequency (the frequency of calling the GetStatus API).

To accommodate this in the add-on, it would require significant modifications to maintain internal state and send at a frequency other than the automatic polling frequency. Let me think about whether be can support this.

Regarding "yields a configuration error" I recommend raising them as issues on the MQTT Integration side.

On a slightly different note, apart from MQTT devices, couldn't you define a filter sensor to achieve sensors with the desired frequency of data points? (I haven't used it myself)
https://www.home-assistant.io/integrations/filter/

**Comment by hsakoh** [comment]
For that purpose, you would need to actually capture temperature changes, so you can only increase the automatic polling frequency. In the device configuration on the Ingress page, specify intervals such as every 1 minute (PT1M) or every 15 seconds (PT15S).

However, please note that the SwitchBot API has a limit of a maximum of 10,000 requests per day, so extremely high-frequency polling is not feasible.

Additionally, based on my logs, the actual measurement frequency of Hub2 has never been shorter than 5 minutes.
(When exporting to CSV in the smartphone app, you can select every minute, so it’s possible that measurements are taken every minute.)

**Comment by hsakoh** [comment]
https://github.com/hsakoh/switchbot-mqtt/blob/main/INSTALLATION.md#physical-devices
![image](https://github.com/hsakoh/switchbot-mqtt/assets/20980395/f4f622c5-4ba7-4d0f-b838-ced30d74d6c6)
