### ISSUE TITLE
OSv12.4 - Error: SwitchBot-Mqtt has been removed from the repository

### ISSUE THREAD

**Issue by BillyFKidney** [hsakoh/switchbot-mqtt#24]
After upgrading the OS to v12.4 the following error has appeared:

<img width="574" alt="image" src="https://github.com/hsakoh/switchbot-mqtt/assets/65253277/97b326e6-0030-4e84-88da-9db43cc2da45">

The repository exists within the Add-On Store:
![image](https://github.com/hsakoh/switchbot-mqtt/assets/65253277/3185c04f-5b0e-4a21-885a-b67ce243e59a)

**Home Assistant**
Core: 2024.6.4
Supervisor: 2024.06.0
Operating System: 12.4
Frontend: 20240610.1

**Comment by hsakoh** [comment]
Thank you for your feedback. I was able to confirm the issue on my end as well.

It seems that the problem was caused by a typo when I added ARM 32bit support last night.
I mistakenly wrote `amdv7` instead of `armv7` in the config.yaml. I have just fixed it.
https://github.com/hsakoh/ha-addon/blob/main/switchbot-mqtt/config.yaml#L15C5-L15C10

The supervisor must have identified the config.yaml as invalid due to the incorrect architecture name.
You may have seen warnings about `amdv7` in the supervisor logs.

Please try restarting HA-OS, which should resolve the warning. Could you confirm this?

**Comment by BillyFKidney** [comment]
Rebooted and received the update.
Thanks for the quick fix!
<img width="1014" alt="image" src="https://github.com/hsakoh/switchbot-mqtt/assets/65253277/23146ac9-4765-4b46-8f06-49b217260b53">
