### ISSUE TITLE
Infrared Air Purifier Missing Speed 1 - 3

### ISSUE THREAD

**Issue by rumpadunk** [hsakoh/switchbot-mqtt#57]
Suddenly the fan speeds for my air purifier disappeared. They were working, now they no longer show up. It's a custom infrared air purifier. The buttons still exist and work in the Swtichbot app, but in the switchbot-mqtt the tag command has changed to undifiend KeySet (6) undifiend KeySet (8) undifiend KeySet (10).

I tried creating a new test device and confirmed in the new device menu 6,8,10 are not present and there is no other option that represent fan speed. The complete list of commands I have:

  | AIR_Power (1) |  
  | AIR_Auto (3) |  
  | AIR_AirVol (5) |  
  | AIR_Timer (7) |  
  | AIR_Mode (9) |  
  | AIR_Anion (11) |  
  | AIR_Comfort (13) |  
  | AIR_mute (15) |  
  | AIR_LEDOFF (17) |  
  | AIR_Force (19) |  
  | AIR_Nature (21) |  
  | AIR_Close (23) |  
  | AIR_Sleep (25) |  
  | AIR_smart (27) |  
  | AlR_Light1 (29) |  
  | AlR_Light2 (31) |  
  | AIR_Light3 (33) |  
  | AIR_UV (35) | 

I tried a few custom commands but couldn't come up with anything. Any ideas? This stopped working a few weeks to ~months ago. I can't recall exactly.

When I capture the call to /wonder/executeRecord/createDeviceRecord it has this in the params for Speed 3:

  "command" : {
    "cmdType" : "tag",
    "deviceCmd" : "10",
    "parameter" : "default"
  },
  
  
  
  Yet when I call tag with 10 and paramenter Default (hardcoded in your app) I get back {"statusCode":160,"message":"unknown command"}.

**Comment by hsakoh** [comment]
Could you provide more details?  
When you say that the fan speed is gone, do you mean the fan speed control button on the MQTT device in Home Assistant?  
Or do you mean it is not included in the Tag's KeySet on the add-on's device configuration screen?  

If it's the former:  
- On the add-on's device configuration screen, is the checkbox in the "Enable" column for rows like `undefined KeySet (6)` checked?  
- Does the issue persist even after restarting the add-on?  

If it's the latter:  
- Since there haven't been any recent changes to the add-on's implementation or updates to the Tag candidate master on the add-on, I believe the "undefined" display has been there from the beginning.  
  [KeySetDefinition.csv](https://github.com/hsakoh/switchbot-mqtt/blob/main/src/SwitchBotMqttApp/MasterData/KeySetDefinition.csv#L234-L251)  

- Even if you re-fetch on the add-on's device configuration screen, the customized parts should not change.  
- Was it working in the past?  
- Could it be that something was accidentally deleted, making it impossible to return to the previous working state?  

By the way, if the add-on is installed as an add-on on HA-OS, the configuration information is stored here:  
`/mnt/data/supervisor/addons/data/cafb8c58_switchbot_mqtt/`  
Since past versions are also stored, you might be able to restore it from here.

**Comment by hsakoh** [comment]
To determine the specific command to send, I’d like to check the data on your customized air purifier from the SwitchBot server.  
More specifically, I’d like to see the response retrieved from `https://{Wonderlabs EndPoint}/homepage/v1/device/remoteinfo`.

There is a tool available for this purpose.  
Could you download the following HTML and operate it in Chrome?  
[https://gist.github.com/hsakoh/7e7d4da41a565a31eb24d7bd08bbcad3](https://gist.github.com/hsakoh/7e7d4da41a565a31eb24d7bd08bbcad3)

---

Since calling the SwitchBot API from a browser encounters CORS blocking issues,  
you’ll need to launch Chrome with CORS disabled using a command like this:  
`"C:\Program Files\Google\Chrome\Application\chrome.exe" --disable-web-security`

This HTML saves data in the browser's storage and only sends external communications emulating the app to SwitchBot.

1. Enter your **Email Address** and **Password**, then click the **Login** button.  
   - Once the access token and refresh token are displayed, click the **Save Tokens** button.

2. Click the **User Info** button to identify the user's **BotRegion**.  
   - Next, click the **Endpoint** button to identify the endpoint for each region.  
   - Once the **Wonderlabs Endpoint** is displayed, click the **Save BotRegion/Endpoints** button.

3. Click the **GroupGetAll** button to list all groups.  
   - Then, click the **DeviceGetAll** button.  
   - When the list of devices and virtual IR devices is displayed, click the **Save Groups/Devices** button.

4. From the dropdown menu, select your air purifier, then click the **Get RemoteInfo** button.  
   - I’d like to see the JSON displayed at this point. (Please mask any personal information such as userID, userName, roomID, remoteID, ownerUserID, etc.)

**Comment by rumpadunk** [comment]
Thanks for the reply. 

Yes, this worked before. 
No changes were made. It just stopped working.
I meant that it is no longer present as a tag in switchbot-mqtt, where it was before. Previously I clicked it in the dropdown and I noticed it's no longer an option since it stopped working.

Here is the json (neat cool by the way):

{
  "acType": "0",
  "brandEn": "no_brand",
  "code": "no_data",
  "codeType": "3",
  "createTime": "202403291546",
  "dbVersion": 29,
  "environmentDataEnable": true,
  "groupID": "<redacted>",
  "keyDetail": [
    {
      "code": "H4sIAAAAAAAAEzMw8Pz7v7LJsFFKWUVZVREZZilDYDaclaWsqgSWUwJjJVQ1nSeaDBv6lKe3gCmGbwwMDABrlqG6XgAAAA==",
      "codeType": "3",
      "keyName": "8",
      "keyType": "key"
    },
    {
      "code": "H4sIAAAAAAAAEzMw8Pz7v7LJsFFKWVURCJVUlFUgLMUsZVSoqgTCQAhVBeShqOk82WTY0KfM8I+BgQEAay81o1cAAAA=",
      "codeType": "3",
      "keyName": "10",
      "keyType": "key"
    },
    {
      "code": "H4sIAAAAAAAAEzMw8Pz7v7LJsFFKWVVJVRGMFcG0UpZylnK2YrYiiAZBkBhUFqwCIZcNZneebDJs6Fea3gKh2poMGvqUGb4yMDAAAFsts7dlAAAA",
      "codeType": "3",
      "keyName": "4",
      "keyType": "key"
    },
    {
      "code": "H4sIAAAAAAAAEzMw8Pz7v6rJsFFKWQUNZgFhtmIWhFaC0FnKqkrZSqpKMDWqQHGYys4TTYYN/UoMzAwMDACOkNmqVwAAAA==",
      "codeType": "3",
      "keyName": "6",
      "keyType": "key"
    },
    {
      "code": "H4sIAAAAAAAAEzMw8Pz7v6pJv1FGUUVZRQkMlUFQVTFbMUs5SxlBZgNlshVBMhCoAhRXhcqC5DtPNRk29CtO72oyaOhXYvjJwMAAALS4GIxeAAAA",
      "codeType": "3",
      "keyName": "FAN SPEED 4",
      "keyType": "text"
    },
    {
      "code": "H4sIAAAAAAAAEzMw8Pz7v7LJsFFKWVURCJVApIoyECplKWcpZysiSJBMtqIqHIJEISREvvNkk2FDn/L0VjDF8ImBgQEA/XsIdF4AAAA=",
      "codeType": "3",
      "keyName": "FAN SPEED 5",
      "keyType": "text"
    },
    {
      "code": "H4sIAAAAAAAAEzMw8Pz7v7LJsFFaURUIVZQRMEs5WylbMQtEK4JokEiWsqpitpIqWG0WVBVQBCzfebLJsKFfkeE7AwMDANTwcFJXAAAA",
      "codeType": "3",
      "keyName": "FAN SPEED 6",
      "keyType": "text"
    }
  ],
  "keyMap": "noKeyMap",
  "parentHubMac": "<redacted>",
  "priority": "0",
  "remoteID": "<redacted>",
  "remoteName": "Air Purifier",
  "serial": 0,
  "sn": "<redacted>",
  "type": 23,
  "unLearnKeyEnable": false,
  "userID": "<redacted>",
  "userName": "<redacted>",
  "vibrateEnable": true,
  "zipCodeVersion": 10
}

Here is a screenshot of the device.
<img width="1140" alt="image" src="https://github.com/user-attachments/assets/c433898f-ead4-4805-a95d-451e8d41d9fc">

Speed 4, 5, 6 work normally as they always did (they are custom buttons I had to create in Switchbot). Speed 1, 2, 3 do not.

I also created a new test air purifier and confirmed that 6, 8, 10 do not show in the switchbot-mqtt dropdown when I retrieve it.

**Comment by rumpadunk** [comment]
Welp, just fixed it.

After seeing the JSON I tried "Customize" with 6, 8, and 10. That works as expected. I have no idea why. It used to work as a tag, now it doesn't and seems it must be "Customize".

Thanks for getting me in the right direction. We can close this, or if you want anymore information I'll provide what I can.

**Comment by hsakoh** [comment]
Thank you for sharing the information.
I’m glad to hear the tool worked well for you.

Looking at the JSON, it seems that items with keyType=key could potentially be called using the Tag command...
But it appears they can’t be called in your environment. I wonder why.

It might be that self-learned keys, which are not generated from the database, can no longer be called with the Tag command and now require the Customize command instead.

For the virtual infrared devices I have, this hasn’t been the case so far, but considering the possibility of staggered rollout by region, this is very insightful.

**Comment by hsakoh** [comment]
As additional information, in my environment, there was also a change in the API functionality. 
The Type=Tag no longer works, and it now operates by specifying the KeySet number with Type=Customize.

By making the following changes and restarting the add-on, it is possible to continue using it without performing maintenance such as deleting MQTT devices. 

Before:
![image](https://github.com/user-attachments/assets/8f8f9509-bb1b-4ea7-b689-31a67b2b958f)

After:
![image](https://github.com/user-attachments/assets/9a982a79-6b63-402f-85b7-a0a6b980f108)

The key point is to maintain the order of the buttons. The order of the buttons on this screen affects the ID of the MQTT devices detected by HomeAssistant.
