### ISSUE TITLE
AddOn does not connect

### ISSUE THREAD

**Issue by JHD47804** [hsakoh/switchbot-mqtt#62]
[cafb8c58_switchbot_mqtt_2024-12-17T00-59-53.769Z.log](https://github.com/user-attachments/files/18158803/cafb8c58_switchbot_mqtt_2024-12-17T00-59-53.769Z.log)
Hi,
The AddOn hasn't been working for a few days, services aren't starting in ServiceManagement. I'm attaching the log file. Please help
Thanks
![Screenshot 2024-12-17 021317](https://github.com/user-attachments/assets/e36f0793-db5f-4af3-88d1-6c6827ed3a7d)

**Comment by hsakoh** [comment]
From what I can see in the logs, it appears to be the same issue as #61.
(Based on my detection, the issue occurred at 06:47:03 (UTC) on December 16, 2024.)
I believe temporarily resolving the issue is possible by updating the add-on and changing the base URL for the API.

You mentioned "a few days," but could you clarify more specifically when this started happening?
There may be an additional issue occurring.

**Comment by hsakoh** [comment]
The API issue has been resolved, so it should function with the original configuration. 
Please revert the API base address to the default `https://api.switch-bot.com/v1.1/`. 

If there is no additional information, it will be closed in a few days.

**Comment by JHD47804** [comment]
Thank you very much, it works again, Merry Christmas
